server:
  port: 9085
spring:
  application:
    name: exam-service
  datasource:
    # ============ LOCAL DEVELOPMENT (IntelliJ IDEA) ============
    # Uncomment below for running locally on your machine
    url: jdbc:postgresql://localhost:5437/examdb
    username: exam
    password: exam
    
    # ============ DOCKER DEPLOYMENT ============
    # Comment below and uncomment above for local development
#    url: jdbc:postgresql://exam-db:5432/examdb
#    username: exam
#    password: exam
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    # ============ LOCAL DEVELOPMENT (IntelliJ IDEA) ============
    host: localhost
    port: 15673
    
    # ============ DOCKER DEPLOYMENT ============
#    host: rabbitmq
#    port: 15673
  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          notification:
            sliding-window-size: 5
            minimum-number-of-calls: 2
            wait-duration-in-open-state: 5s
app:
  jwt:
    secret: ${JWT_SECRET:TXlfU21hcnRDYW1wdXNfU2VjcmV0X0tleTEyMzQ1Njc4OTAxMjM0NTY3OA==}
  notification:
    # ============ LOCAL DEVELOPMENT (IntelliJ IDEA) ============
    url: http://localhost:9086
    
    # ============ DOCKER DEPLOYMENT ============
    # Uncomment below for Docker deployment
#    url: http://notification-service:8086

