global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-service:8082"]

  - job_name: booking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["booking-service:8085"]

  - job_name: marketplace-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["marketplace-service:8086"]

  - job_name: exam-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["exam-service:8087"]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8088"]

  - job_name: dashboard-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["dashboard-service:8089"]

