server:
  port: 9086
spring:
  application:
    name: notification-service
  datasource:
    # ============ LOCAL DEVELOPMENT (IntelliJ IDEA) ============
    # Uncomment below for running locally on your machine
    url: jdbc:postgresql://localhost:5438/notificationdb
    username: note
    password: note
    
    # ============ DOCKER DEPLOYMENT ============
    # Comment below and uncomment above for local development
#    url: jdbc:postgresql://notification-db:5432/notificationdb
#    username: note
#    password: note
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    # ============ LOCAL DEVELOPMENT (IntelliJ IDEA) ============
    host: localhost
    port: 15673
    
    # ============ DOCKER DEPLOYMENT ============
#    host: rabbitmq
#    port: 15673
app:
  jwt:
    secret: ${JWT_SECRET:TXlfU21hcnRDYW1wdXNfU2VjcmV0X0tleTEyMzQ1Njc4OTAxMjM0NTY3OA==}

