version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE: http://localhost:9080
    ports:
      - "4173:80"
    container_name: smart-campus-ui
    restart: unless-stopped

